#!/bin/env bash

scripts=0
logs=0
configs=0
others=0

while IFS= read -r filename; do
    case "$filename" in
        *.sh)
            (( scripts++ ))
            ;;
        *.log)
            (( logs++ ))
            ;;
        *.conf)
            (( configs++ ))
            ;;
        *)
            (( others++ ))
            ;;
    esac
done

echo "Scripts (.sh): $scripts"
echo "Logs (.log): $logs"
echo "Configs (.conf): $configs"
echo "Others: $others"
